segunda_entrega/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('titles/', include('titles.urls')),
    path('admin/', admin.site.urls),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'), 
    path('', views.index, name='index'),
]

titles/urls.py
from django.urls import path

from . import views

app_name = 'titles'
urlpatterns = [
    path('', views.TitleListView.as_view(), name='index'),
    path('search/', views.search_titles, name='search'),
    path('create/', views.create_title, name='create'),
    path('<int:title_id>/', views.detail_title, name='detail'),
    path('update/<int:title_id>/', views.update_title, name='update'),
    path('delete/<int:title_id>/', views.delete_title, name='delete'),
    path('<int:title_id>/review/', views.create_review, name='review'),
    path('lists/', views.ListListView.as_view(), name='lists'),
    path('lists/create', views.ListCreateView.as_view(), name='create-list'),
]

staticpages/models.py
from django.db import models

# Create your models here.

titles/models.py
from django.db import models
from django.conf import settings


class Title(models.Model):
    name = models.CharField(max_length=255)
    year = models.IntegerField()
    title_photo = models.URLField(max_length=200, null=True)

    def __str__(self):
        return f'{self.name} ({self.year})'


class Review(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    likes = models.IntegerField(default=0)
    title = models.ForeignKey(Title, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

class List(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    titles = models.ManyToManyField(Title)

    def __str__(self):
        return f'{self.name} by {self.author}'

titles/forms.py
from django import forms
from django.forms import ModelForm
from .models import Title, Review

class TitleForm(ModelForm):
    class Meta:
        model = Title
        fields = [
            'name',
            'year',
            'title_photo',]
        labels = {
            'name': 'Título',
            'year': 'Ano da conquista',
            'title_photo': 'Foto do título',}

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Comentário',
        }

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

titles/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .temp_data import title_data
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .models import Title, Review, List
from django.views import generic
from .forms import TitleForm, ReviewForm

def list_titles(request):
    title_list = Title.objects.all()
    context = {'title_list': title_list}
    return render(request, 'titles/index.html', context)

def detail_title(request, title_id):
    title = get_object_or_404(Title,pk=title_id)
    context = {'title': title}
    return render(request, 'titles/detail.html', context)

def search_titles(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        title_list = Title.objects.filter(name__icontains=search_term)
        context = {"title_list": title_list}
    return render(request, 'titles/search.html', context)

def create_title(request):
    form = TitleForm(request.POST)
    if request.method == 'POST':
        title_name = form.cleaned_data['name']
        title_year = form.cleaned_data['year']
        title_title_photo = form.cleaned_data['title_photo']
        title = Title(name = title_name, year = title_year, title_photo = title_title_photo)
        title.save()
        return HttpResponseRedirect(
            reverse('titles:detail', args=(title.id, )))
    else:
        form = TitleForm()
        context = {'form': form}
        return render(request, 'titles/create.html', context)

def update_title(request, title_id):
    title = get_object_or_404(Title, pk=title_id)

    if request.method == "POST":
        form = TitleForm(request.POST)
        if form.is_valid():
            title.name = request.POST['name']
            title.year = request.POST['year']
            title_title_photo = request.POST['title_photo']
            title.save()
            return HttpResponseRedirect(
                reverse('titles:detail', args=(title.id, )))
    else:
        form = TitleForm(
            initial={
                'name': title.name,
                'release_year': title.release_year,
                'poster_url': title.poster_url
            })

    context = {'title': title, 'form': form}
    return render(request, 'titles/update.html', context)


def delete_title(request, title_id):
    title = get_object_or_404(Title, pk=title_id)

    if request.method == "POST":
        title.delete()
        return HttpResponseRedirect(reverse('titles:index'))

    context = {'title': title}
    return render(request, 'titles/delete.html', context)

class TitleListView(generic.ListView):
    model = Title
    template_name = 'titles/index.html'

def create_review(request, title_id):
    title = get_object_or_404(Title, pk=title_id)
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review_author = form.cleaned_data['author']
            review_text = form.cleaned_data['text']
            review = Review(author=review_author,
                            text=review_text,
                            title=title)
            review.save()
            return HttpResponseRedirect(
                reverse('titles:detail', args=(title_id, )))
    else:
        form = ReviewForm()
    context = {'form': form, 'title': title}
    return render(request, 'titles/review.html', context)

class ListListView(generic.ListView):
    model = List
    template_name = 'titles/lists.html'


class ListCreateView(generic.CreateView):
    model = List
    template_name = 'titles/create_list.html'
    fields = ['name', 'author', 'titles']
    success_url = reverse_lazy('titles:lists')

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>
<p>Aqui teremos desde os títulos até os principais jogadores, fique ligado!</p>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>Blog do Flamengo</i></h1>
<p>A Página para admirar o maior clube do país</p>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} Blog do Mengão!
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> 
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'clube-regatas-flamengo.svg' %}"> </a>
        <h1>Blog do Mengão!</h1>  
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'titles:index' %}">Títulos</a></li> 
                <li><a href="{% url 'titles:lists' %}">Listas</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2022</small>
        </p>
    </footer>
</body>

</html>

titles/templates/titles/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Título</h2>
<form method="POST" action="{% url 'titles:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

titles/templates/titles/create_list.html
{% extends 'base.html' %}

{% block title %}
Criar Título
{% endblock title %}

{% block content %}
<h2>Criar Lista</h2>

<form action="{% url 'titles:create-list' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

titles/templates/titles/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'titles:delete' title.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar o título "{{ title.name }} ({{ title.year }})"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

titles/templates/titles/detail.html
{% extends 'base.html' %}

{% block title %}
{{ title.name }} ({{ title.year }}
{% endblock title %}

{% block content %}
<h2>Detalhes do Título {{ title.name }} ({{ title.year }})</h2>

<section class="dados-de-titulo">
    <img src="{{ title.title_photo }}" alt="Foto do título do(a) {{ title.name}}">
    <ul>
        <li>Título: {{ title.name }}</li>
        <li>Ano da conquista: {{ title.year }} </li>
    {% if title.list_set.all %}
        <li>Incluso nas listas: {{ title.list_set.all|join:", " }} </li>
    {% endif %}

        <li><a href="{% url 'titles:update' title.id %}">Editar</a></li>
        <li><a href="{% url 'titles:delete' title.id %}">Apagar</a></li>
    </ul>
</section>

<hr>

<section>
    <header>
        <h3>Resenhas</h3>
    </header>
    <ul>
        {% if title.review_set.all %}
            {% for review in title.review_set.all %}
                <figure>
                    <blockquote>
                        "{{ review.text }}"
                    </blockquote>
                    <figcaption>—{{ review.author }}
                </figure>
            {% endfor %}
        {% else %}
            <p>Ainda não existe nenhum comentário para este título.</p>
        {% endif %}
    </ul>
    
    <hr>

    <a href="{% url 'titles:review' title.pk %}"><button>Crie seu comentário</button></a>
</section>
    
{% endblock content %}

titles/templates/titles/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos os Títulos</h2>
<section>
    <p>Muitos resultados? <a href="{% url 'titles:search' %}">Buscar Títulos</a></p>
    <p>Não encontrou o título? <a href="{% url 'titles:create' %}">Adicionar Novo Título</a></p>
</section>
{% if title_list %}
<section class="lista-de-cards">
    {% for title in title_list %}
    <article class="card">
        <a href="{% url 'titles:detail' forloop.counter %}"><img src="{{ title.title_photo }}"
                alt="Foto do título {{ title.name}}"></a>
        <p>{{ title.name }} ({{ title.year }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum título.</p>
{% endif %}

{% endblock content %}

titles/templates/titles/lists.html
{% extends 'base.html' %}

{% block title %}
Listas
{% endblock title %}

{% block content %}
<h2>Listas de Títulos</h2>

<section>
    {% for list in list_list %}
    <hr>
    <article>
        <header>
            <h3>{{list.name}} (de {{ list.author }}) </h3>
        </header>
        <div class="lista-de-cards">
            {% for title in list.titles.all %}
            <div class="card">
                <a href="{% url 'titles:detail' title.id %}"><img src="{{ title.title_photo }}"
                        alt="Poster do filme {{ title.name}}"></a>
                <p>{{ title.name }} ({{ title.year }})</p>
            </div>
            {% endfor %}
        </div>
    </article>
    {% endfor %}

    <a href="{% url 'titles:create-list' %}"><button>Crie sua Lista</button></a>
</section>

{% endblock content %}

titles/templates/titles/review.html
{% extends 'base.html' %}

{% block content %}
<h2>Comentar Título {{ title.name }} ({{ title.year }})</h2>

<form action="{% url 'titles:review' title.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar Comentário</button>
</form>

<p><a href="{% url 'titles:detail' title.id %}">Voltar para a página do Título</a></p>
{% endblock content %}

titles/templates/titles/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Títulos por Nome</h2>
<form action="{% url 'titles:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if title_list %}
<section class="lista-de-cards">
    {% for title in title_list %}
    <article class="card">
        <img src="{{ title.title_photo }}" alt="Foto do título {{ title.name}}">
        <p>{{ title.name }} ({{ title.year }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum filme para a busca.</p>
{% endif %}

{% endblock content %}

titles/templates/titles/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Dados do Título {{ title.name }} ({{ title.year}})</h2>
<form method="POST" action="{% url 'titles:update' movie.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}